# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-26 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=9, unique=True),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
