# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-16 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomcategory',
            options={},
        ),
    ]
