# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200616_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rooms.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.RoomCategory'),
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.AddField(
            model_name='invoice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_invoices', to='rooms.Room'),
        ),
    ]
