# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200617_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
