insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lid - High Heat, Super Clear', 31.46, 48, 13, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('The Pop Shoppe - Cream Soda', 86.99, 65, 82, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sprouts Dikon', 48.86, 37, 51, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - White, Ej', 29.23, 16, 34, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Turkey - Whole, Fresh', 51.29, 80, 8, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pate - Peppercorn', 44.13, 47, 46, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mackerel Whole Fresh', 46.0, 72, 8, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Roll, Canadian Dinner', 41.8, 33, 100, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lettuce - Radicchio', 60.79, 41, 49, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Food Colouring - Orange', 33.49, 91, 76, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Appetizer - Escargot Puff', 18.16, 5, 94, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bar Bran Honey Nut', 7.68, 50, 94, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Syrup - Golden, Lyles', 87.79, 49, 1, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Smoked Tongue', 54.77, 47, 66, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread Base - Italian', 91.39, 58, 56, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Ecolab - Hobart Washarm End Cap', 55.97, 11, 11, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Alfredo', 41.16, 59, 67, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Blouse / Shirt / Sweater', 22.75, 43, 22, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soup - Campbells Broccoli', 56.17, 42, 39, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cookie Dough - Chunky', 55.34, 64, 55, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Salt - Celery', 45.32, 24, 48, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lychee', 4.66, 28, 87, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Basil - Primerba, Paste', 87.48, 66, 92, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Kohlrabi', 62.66, 76, 89, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chambord Royal', 46.45, 19, 36, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Butter Sweet', 48.1, 11, 13, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Onions Granulated', 87.54, 12, 52, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Julienne, Frozen', 65.63, 31, 56, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soup - Campbells Beef Strogonoff', 33.02, 25, 73, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cookie - Oatmeal', 49.97, 10, 99, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Nantucket Orange Juice', 96.45, 28, 56, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Nantucket - 518ml', 93.45, 29, 3, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Tio Pepe Sherry Fino', 88.12, 3, 30, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tea - Herbal Sweet Dreams', 33.34, 87, 2, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Juice - Pineapple, 341 Ml', 91.08, 27, 20, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beer - Heinekin', 51.31, 69, 19, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Straws - Cocktale', 31.39, 91, 59, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Milk - Buttermilk', 33.07, 74, 96, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tea - Apple Green Tea', 67.09, 39, 26, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Appetizer - Cheese Bites', 7.85, 96, 66, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Milk - Buttermilk', 73.9, 60, 52, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Onions - Red Pearl', 21.96, 30, 25, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef - Diced', 46.11, 53, 21, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coconut - Shredded, Unsweet', 62.14, 24, 25, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Carbonated Water - Wildberry', 82.36, 58, 55, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Quail - Jumbo', 21.29, 20, 88, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Vodka - Lemon, Absolut', 16.99, 28, 50, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Chili Powder', 24.11, 82, 31, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beer - Mill St Organic', 34.47, 37, 84, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - White, Unsliced', 72.52, 15, 51, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mousse - Passion Fruit', 56.13, 66, 47, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Pumpernickel', 44.36, 54, 47, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Duck - Breast', 34.17, 86, 25, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sprouts - Alfalfa', 8.38, 86, 67, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Foam Tray S2', 29.5, 31, 39, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cod - Black Whole Fillet', 61.04, 90, 71, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Feta', 94.15, 31, 18, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Basil - Pesto Sauce', 90.56, 94, 72, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Roll, Italian', 74.74, 66, 14, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Brie', 79.6, 37, 2, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Gravy, Au Jus, Mix', 20.02, 60, 40, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Placemat - Scallop, White', 66.19, 16, 13, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Stock - Fish', 81.65, 78, 60, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cocoa Feuilletine', 57.09, 81, 34, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef - Tenderlion, Center Cut', 93.11, 66, 96, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Red, Wolf Blass, Yellow', 8.94, 78, 73, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bagelers - Cinn / Brown', 22.98, 82, 22, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sachet', 37.36, 5, 76, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cornflakes', 84.68, 6, 69, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mayonnaise - Individual Pkg', 85.01, 83, 75, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beans - Long, Chinese', 68.18, 100, 57, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Nut - Pine Nuts, Whole', 66.17, 51, 91, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mushroom - Oyster, Fresh', 87.82, 88, 76, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef Cheek Fresh', 79.18, 78, 85, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef Dry Aged Tenderloin Aaa', 66.16, 29, 85, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Flounder - Fresh', 16.66, 94, 96, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sambuca - Ramazzotti', 55.73, 30, 34, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Swiss Sliced', 41.39, 64, 47, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Steel Wool S.o.s', 41.39, 88, 49, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Oil - Canola', 24.11, 41, 30, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Asparagus - Green, Fresh', 80.73, 95, 51, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Milk Powder', 69.0, 85, 51, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Vinegar - Balsamic, White', 21.75, 76, 79, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coconut - Whole', 94.5, 15, 60, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Catfish - Fillets', 31.96, 48, 99, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Orange - Tangerine', 65.39, 46, 70, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Focaccia Quarter', 28.68, 18, 58, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Parasol Pick Stir Stick', 5.78, 7, 68, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Butter Sweet', 83.08, 99, 35, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Squeeze Bottle', 82.14, 92, 28, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Scallop - St. Jaques', 65.2, 69, 92, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Squid - U - 10 Thailand', 15.26, 44, 80, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tofu - Soft', 16.04, 94, 44, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Marjoram - Fresh', 53.59, 2, 87, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef Tenderloin Aaa', 50.13, 6, 95, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Gravy, Au Jus, Mix', 68.1, 17, 44, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cleaner - Lime Away', 69.76, 29, 93, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Maple Syrup', 70.0, 25, 64, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chicken - Leg, Fresh', 65.19, 71, 65, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Nut - Peanut, Roasted', 98.57, 6, 80, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Oil - Macadamia', 64.03, 34, 40, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Placemat - Scallop, White', 80.58, 75, 89, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lady Fingers', 76.87, 50, 55, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pizza Pizza Dough', 34.31, 63, 40, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Puree - Passion Fruit', 66.96, 72, 58, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Red, Colio Cabernet', 65.64, 95, 82, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Eggplant Italian', 47.36, 71, 96, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pea - Snow', 19.44, 12, 13, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chicken - Whole Fryers', 28.83, 30, 55, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Table Cloth 81x81 Colour', 36.15, 71, 92, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Quail - Whole, Boneless', 65.08, 37, 57, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Red, Concha Y Toro', 1.22, 42, 6, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Island Oasis - Sweet And Sour Mix', 71.98, 87, 77, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Compound - Raspberry', 21.61, 41, 73, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coffee Beans - Chocolate', 38.58, 63, 1, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Bistro White', 97.3, 27, 43, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soup - Clam Chowder, Dry Mix', 43.33, 22, 47, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce Tomato Pouch', 70.0, 72, 45, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Tio Pepe Sherry Fino', 53.76, 67, 94, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pop Shoppe Cream Soda', 83.36, 13, 2, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pork - Backs - Boneless', 65.36, 28, 60, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese Cheddar Processed', 17.82, 6, 12, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Appetiser - Bought', 47.35, 91, 81, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread Base - Gold Formel', 85.34, 28, 44, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sherbet - Raspberry', 93.76, 51, 96, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Table Cloth 53x69 White', 11.7, 9, 61, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Almonds Ground Blanched', 71.33, 59, 12, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mousse - Banana Chocolate', 4.69, 95, 23, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beer - Corona', 84.05, 27, 100, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mountain Dew', 28.61, 60, 7, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cake - Pancake', 43.21, 2, 90, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Rosso Toscano Igt', 49.71, 76, 51, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Stock - Veal, White', 73.45, 73, 69, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pastry - Butterscotch Baked', 97.05, 27, 68, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chicken - Leg / Back Attach', 57.57, 54, 28, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pie Filling - Cherry', 46.27, 99, 6, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Juice - Tomato, 48 Oz', 56.06, 70, 62, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pasta - Spaghetti, Dry', 95.93, 33, 36, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Sorrano', 75.81, 54, 79, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Corn - On The Cob', 89.65, 41, 21, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Nut - Pine Nuts, Whole', 30.81, 41, 29, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Leeks - Large', 29.64, 80, 5, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Huck Towels White', 44.99, 35, 7, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Container - Hngd Cll Blk 7x7x3', 31.84, 66, 63, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Prunes - Pitted', 82.92, 27, 81, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Cubanelle', 90.06, 22, 66, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bagel - Plain', 1.37, 40, 3, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Napkin - Beverge, White 2 - Ply', 33.75, 8, 3, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mushroom - King Eryingii', 54.03, 58, 92, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('French Kiss Vanilla', 86.73, 31, 34, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Feta', 10.52, 39, 92, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Zucchini - Yellow', 28.14, 30, 42, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Muffin Hinge - 211n', 67.37, 53, 92, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Yams', 33.56, 94, 54, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Glass Clear 8 Oz', 87.6, 68, 83, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tray - 16in Rnd Blk', 41.39, 5, 97, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bag - Bread, White, Plain', 57.23, 50, 95, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Flour - So Mix Cake White', 20.98, 3, 77, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beets - Mini Golden', 25.6, 51, 10, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Salmon Steak - Cohoe 6 Oz', 83.92, 17, 52, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Thermometer Digital', 26.36, 50, 81, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Asparagus - White, Fresh', 85.46, 70, 49, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pea - Snow', 4.87, 42, 29, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cherries - Frozen', 19.43, 82, 9, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bay Leaf', 10.77, 10, 83, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Creme De Cacao White', 43.97, 61, 13, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('The Pop Shoppe - Cream Soda', 92.74, 66, 58, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Syrup - Pancake', 2.77, 67, 47, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Salad Dressing', 67.65, 42, 90, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Water - Spring 1.5lit', 75.32, 46, 100, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Sawmill Creek Autumn', 58.55, 50, 13, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Muffin - Blueberry Individual', 82.04, 76, 48, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Vinegar - Tarragon', 11.69, 42, 79, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Sauvignon Blanc Oyster', 40.63, 8, 46, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lettuce - Curly Endive', 48.41, 41, 31, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beer - Tetleys', 89.78, 13, 95, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tomato Puree', 62.66, 70, 71, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Versatainer Nc - 9388', 31.4, 97, 79, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Filo Dough', 63.59, 85, 100, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Rum - Light, Captain Morgan', 4.68, 51, 62, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mushroom - Trumpet, Dry', 15.33, 66, 49, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cherries - Maraschino,jar', 39.55, 31, 30, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Goat', 92.96, 75, 100, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Island Oasis - Peach Daiquiri', 58.21, 2, 3, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Kimel Stick Poly', 11.21, 15, 24, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Chilli Seeds Mild', 47.44, 97, 15, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Veal - Kidney', 19.01, 96, 55, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Water Chestnut - Canned', 41.78, 78, 60, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Broom And Broom Rack White', 84.01, 67, 24, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Steampan Lid', 58.76, 65, 73, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sambuca Cream', 42.37, 64, 26, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Snails - Large Canned', 65.22, 16, 40, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coffee - Irish Cream', 9.86, 57, 5, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Flounder - Fresh', 11.77, 10, 64, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Piping - Bags Quizna', 20.01, 59, 66, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Fireball Whisky', 93.85, 32, 90, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Grenadillo', 94.57, 73, 83, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sugar - Brown', 23.11, 13, 59, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Crumbs, Bulk', 80.24, 63, 71, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread Sour Rolls', 37.04, 4, 97, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Chablis 2003 Champs', 66.57, 81, 54, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Pinot Grigio Collavini', 41.21, 55, 2, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Swordfish Loin Portions', 94.64, 81, 40, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Olives - Stuffed', 88.39, 77, 69, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sprite, Diet - 355ml', 32.64, 30, 75, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Rosemary - Dry', 18.2, 46, 83, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Black Tower Qr', 59.12, 56, 37, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pasta - Lasagne, Fresh', 81.43, 55, 9, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Capon - Breast, Wing On', 67.29, 92, 66, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chicken - Base', 63.96, 91, 81, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Charddonnay Errazuriz', 17.67, 98, 73, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - White, Gewurtzraminer', 35.47, 99, 97, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Toamtoes 6x7 Select', 96.26, 98, 11, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - 10 Grain Parisian', 83.01, 79, 13, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Savigny - Les - Beaune', 46.19, 98, 85, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Juice - Cranberry, 341 Ml', 67.94, 73, 87, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mussels - Cultivated', 91.23, 89, 38, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Brandy Apricot', 53.36, 53, 76, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Fish 25 Ozf Bottle', 92.95, 59, 14, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Truffle - Peelings', 66.09, 8, 49, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cookies Oatmeal Raisin', 85.2, 91, 76, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Peach - Fresh', 28.37, 92, 61, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Red, Concha Y Toro', 83.84, 32, 98, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Scallops - Live In Shell', 36.46, 83, 52, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sea Bass - Whole', 23.95, 59, 33, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Liqueur Banana, Ramazzotti', 78.43, 17, 82, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tuna - Yellowfin', 50.25, 63, 31, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coffee - Decafenated', 8.15, 81, 86, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Ice Cream - Life Savers', 9.81, 96, 4, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Casablanca Valley', 59.88, 85, 53, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - French Baquette', 16.39, 14, 70, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Energy Drink Red Bull', 17.5, 58, 20, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Doilies - 7, Paper', 71.59, 82, 83, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Veal - Leg, Provimi - 50 Lb Max', 47.74, 59, 37, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Demi Glace', 58.12, 27, 97, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cup - 3.5oz, Foam', 37.28, 19, 58, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('True - Vue Containers', 32.75, 53, 43, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Doilies - 7, Paper', 6.19, 56, 50, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tomato - Green', 35.84, 44, 4, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - German Riesling', 33.51, 23, 36, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Trueblue - Blueberry 12x473ml', 51.77, 85, 41, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Evaporated Milk - Skim', 41.05, 99, 71, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Taro Root', 1.23, 93, 16, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Veal - Leg, Provimi - 50 Lb Max', 54.35, 23, 34, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sausage - Blood Pudding', 96.52, 19, 63, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pike - Frozen Fillet', 34.54, 27, 13, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mace Ground', 59.75, 21, 41, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cookie Double Choco', 2.89, 99, 18, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Dish Towel', 85.98, 95, 56, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mushroom - Porcini Frozen', 51.52, 66, 79, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pastry - French Mini Assorted', 87.74, 45, 68, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Milkettes - 2%', 14.75, 32, 19, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Catfish - Fillets', 84.4, 35, 60, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Pita', 58.72, 7, 64, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef Wellington', 66.89, 22, 100, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sugar - Crumb', 56.73, 60, 60, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Balbach Riverside', 78.21, 39, 35, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Puree - Mocha', 96.69, 60, 93, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Veal - Round, Eye Of', 81.24, 93, 26, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pasta - Cannelloni, Sheets, Fresh', 20.9, 21, 48, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Fenngreek Seed', 31.65, 57, 99, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Brie, Cups 125g', 3.83, 56, 12, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Yogurt - Strawberry, 175 Gr', 1.56, 13, 63, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cake - Miini Cheesecake Cherry', 96.76, 77, 29, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Shrimp - 16 - 20 Cooked, Peeled', 36.65, 4, 55, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Butter - Salted', 83.89, 87, 62, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beets - Candy Cane, Organic', 23.82, 55, 85, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pork - Belly Fresh', 81.12, 23, 52, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Savigny - Les - Beaune', 82.68, 8, 34, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Scampi Tail', 85.64, 70, 30, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Appetizer - Spring Roll, Veg', 24.88, 91, 76, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Broccoli - Fresh', 87.95, 42, 8, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cloves - Ground', 86.31, 14, 29, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Green, Chili', 27.46, 90, 39, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sobe - Tropical Energy', 55.12, 89, 11, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Aromat Spice / Seasoning', 96.03, 95, 40, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tart Shells - Sweet, 4', 31.15, 41, 96, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soup - Campbells, Minestrone', 97.22, 57, 50, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Prosecco Valdobiaddene', 63.67, 90, 89, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Muffin - Mix - Mango Sour Cherry', 80.85, 27, 5, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Creme De Cacao Mcguines', 87.05, 27, 90, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Petit Baguette', 48.21, 2, 47, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - White, Pinot Grigio', 99.39, 68, 21, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Muscadet Sur Lie', 66.14, 85, 25, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Roasted Red', 72.72, 7, 29, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Red Snapper - Fresh, Whole', 86.98, 64, 26, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Duck - Breast', 51.81, 52, 98, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Artichoke - Fresh', 98.54, 21, 94, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Water - San Pellegrino', 81.96, 47, 28, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Slt - Individual Portions', 15.79, 28, 90, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef - Tenderlion, Center Cut', 55.13, 11, 65, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Flour - Fast / Rapid', 54.54, 71, 91, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Eggroll', 50.79, 68, 70, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Muffin - Mix - Creme Brule 15l', 48.6, 34, 15, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sansho Powder', 46.05, 70, 31, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Squash - Pattypan, Yellow', 98.57, 77, 91, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Shrimp - 100 / 200 Cold Water', 40.88, 48, 7, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Marinara', 87.25, 59, 95, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coconut Milk - Unsweetened', 8.38, 10, 63, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Oil - Safflower', 17.73, 72, 17, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread Country Roll', 26.2, 83, 74, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pork - Belly Fresh', 41.48, 86, 72, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Red, Harrow Estates, Cab', 80.9, 66, 2, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sour Puss Sour Apple', 9.7, 79, 10, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Soya, Dark', 38.02, 81, 34, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lid Tray - 16in Dome', 99.59, 16, 13, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread Crumbs - Panko', 89.58, 76, 33, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pasta - Linguini, Dry', 72.43, 5, 12, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Barbera Alba Doc 2001', 23.94, 86, 23, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chocolate Bar - Oh Henry', 79.18, 100, 75, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Kellogs Special K Cereal', 1.0, 83, 82, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soup - Campbells, Cream Of', 58.9, 43, 11, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Juice - V8 Splash', 4.23, 50, 30, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Shrimp - Black Tiger 13/15', 30.99, 56, 71, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tomatoes', 99.98, 42, 45, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Eel Fresh', 23.97, 35, 2, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Veal - Heart', 65.73, 80, 9, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('The Pop Shoppe Pinapple', 43.74, 26, 33, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lobster - Tail 6 Oz', 41.46, 65, 62, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Appetizer - Mango Chevre', 40.39, 34, 63, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Haggis', 30.53, 43, 73, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Puff Pastry - Slab', 59.7, 24, 28, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef - Shank', 72.31, 52, 1, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sugar - Sweet N Low, Individual', 31.52, 58, 74, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - 10 Grain', 8.43, 85, 44, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tea - Mint', 73.32, 41, 89, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Juice - Cranberry 284ml', 62.57, 65, 11, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Barolo Fontanafredda', 99.57, 16, 78, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Table Cloth 81x81 White', 92.11, 54, 92, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Flavouring - Rum', 72.49, 25, 79, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chinese Lemon Pork', 25.13, 62, 86, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cups 10oz Trans', 53.59, 61, 47, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Laundry - Bag Cloth', 45.41, 38, 49, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beer - Moosehead', 67.55, 48, 23, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Crab - Dungeness, Whole', 68.86, 2, 69, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pork - Smoked Kassler', 76.87, 58, 7, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Garlic - Peeled', 73.12, 55, 93, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beets - Mini Golden', 62.48, 87, 33, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef - Striploin', 94.28, 22, 96, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Rye', 30.03, 64, 30, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Perron Cheddar', 40.57, 96, 48, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Goat With Herbs', 58.12, 19, 54, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Split Peas - Green, Dry', 22.94, 31, 80, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chickhen - Chicken Phyllo', 57.58, 65, 68, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soap - Mr.clean Floor Soap', 11.5, 100, 37, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Ostrich - Fan Fillet', 44.92, 72, 59, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wasabi Paste', 23.93, 51, 89, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Water - Evian 355 Ml', 47.21, 19, 29, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Calypso - Lemonade', 72.96, 52, 66, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Glycerine', 29.35, 100, 56, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pimento - Canned', 1.88, 10, 7, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coffee - Irish Cream', 21.28, 77, 79, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Peas Snow', 78.04, 91, 95, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Turnip - White', 22.41, 99, 75, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lid - Translucent, 3.5 And 6 Oz', 14.15, 59, 68, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chinese Foods - Cantonese', 99.08, 29, 20, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Kippers - Smoked', 94.07, 16, 72, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Water - Evian 355 Ml', 7.8, 20, 32, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sherry - Dry', 21.45, 54, 58, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tea - Mint', 39.84, 76, 39, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pasta - Fusili Tri - Coloured', 12.67, 52, 94, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('The Pop Shoppe - Cream Soda', 87.63, 32, 59, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Redchard Merritt', 96.09, 57, 2, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lettuce Romaine Chopped', 86.19, 9, 34, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pork - Kidney', 22.5, 32, 46, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soup Campbells', 60.01, 79, 8, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tomato - Tricolor Cherry', 25.0, 85, 93, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Nantucket Pine Orangebanana', 77.4, 49, 18, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beans - Navy, Dry', 56.48, 14, 67, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cognac - Courvaisier', 84.56, 89, 22, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pasta - Orecchiette', 29.13, 13, 35, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Comte', 28.27, 53, 4, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chicken - Bones', 43.85, 65, 93, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chocolate - Milk, Callets', 66.21, 53, 64, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Mustard - Seed', 78.9, 44, 43, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cookie Choc', 24.9, 72, 50, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beans - Black Bean, Preserved', 71.35, 34, 32, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lettuce - Arugula', 64.4, 92, 71, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Two Oceans Sauvignon', 19.92, 6, 28, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soup Campbells Turkey Veg.', 6.96, 84, 31, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Monkfish Fresh - Skin Off', 3.79, 44, 79, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Apron', 92.46, 81, 100, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Truffle Cups - Red', 68.68, 20, 45, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Salmon Steak - Cohoe 8 Oz', 96.42, 45, 86, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bacardi Breezer - Tropical', 29.14, 80, 38, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coffee - Decafenated', 99.47, 88, 67, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Juice - Orange', 2.59, 39, 44, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Red Cod Fillets - 225g', 38.71, 75, 15, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Raspberries - Fresh', 34.52, 42, 1, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('French Pastries', 56.82, 55, 9, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Soup - Campbellschix Stew', 43.63, 84, 94, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Cabernet Sauvignon', 41.13, 11, 16, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Spice - Chili Powder Mexican', 59.4, 12, 77, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Salmon Steak - Cohoe 8 Oz', 7.04, 70, 52, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Papayas', 53.43, 57, 50, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Liners - Baking Cups', 91.41, 92, 23, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Ecolab Silver Fusion', 24.05, 15, 60, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Trimbach Pinot Blanc', 85.73, 43, 59, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Hagen Daza - Dk Choocolate', 71.07, 3, 21, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Table Cloth 81x81 Colour', 47.09, 17, 59, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Stock - Veal, White', 24.79, 57, 39, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Nut - Pecan, Halves', 93.46, 23, 17, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Champagne Brut Veuve', 85.73, 14, 45, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chips - Doritos', 96.04, 92, 31, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Cabernet Sauvignon', 4.65, 11, 38, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Gravy, Au Jus, Mix', 35.86, 86, 52, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Steam Pan Full Lid', 88.06, 27, 59, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Red Thai', 69.75, 41, 98, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coffee - Dark Roast', 6.54, 80, 50, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beef - Montreal Smoked Brisket', 92.17, 31, 14, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Cousino Macul Antiguas', 71.28, 79, 58, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Corn - On The Cob', 39.98, 1, 96, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lettuce - Curly Endive', 91.68, 13, 32, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tea - Grapefruit Green Tea', 45.38, 28, 22, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pork Salted Bellies', 36.97, 41, 44, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Coffee - Espresso', 77.67, 40, 88, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Muskox - French Rack', 68.19, 1, 33, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Dried Apple', 69.19, 69, 31, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Water - Tonic', 21.54, 90, 93, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pork - Bones', 16.95, 68, 17, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Veal - Bones', 2.33, 81, 45, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Calaloo', 78.61, 66, 10, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bar Special K', 34.31, 68, 95, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Carbonated Water - Blackcherry', 35.38, 28, 25, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Milk - Homo', 29.36, 28, 94, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Crackers - Soda / Saltins', 23.16, 10, 12, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Higashimaru Usukuchi Soy', 97.64, 42, 77, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Carbonated Water - Strawberry', 86.95, 70, 24, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Multigrain, Loaf', 94.57, 50, 78, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Glass Clear 7 Oz Xl', 39.58, 18, 9, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Oyster', 57.39, 63, 99, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Chili Powder', 64.86, 95, 73, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bacardi Limon', 56.26, 9, 27, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('French Pastry - Mini Chocolate', 98.62, 92, 10, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Yogurt - Cherry, 175 Gr', 80.42, 23, 75, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Rosemary Focaccia', 53.64, 34, 57, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Breakfast Quesadillas', 20.02, 40, 88, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pork - Smoked Kassler', 79.52, 94, 43, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Appetizer - Crab And Brie', 19.8, 50, 56, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sauce - Apple, Unsweetened', 91.15, 98, 58, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Silicone Parch. 16.3x24.3', 53.92, 49, 23, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chinese Foods - Chicken Wing', 47.34, 7, 38, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Burger Veggie', 82.66, 62, 65, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lettuce - Lambs Mash', 17.94, 19, 77, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pectin', 95.43, 27, 28, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pail - 15l White, With Handle', 36.64, 2, 73, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Roe - Flying Fish', 89.28, 82, 29, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Ecolab - Lime - A - Way 4/4 L', 8.74, 14, 60, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lamb Tenderloin Nz Fr', 66.13, 43, 11, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Flower - Daisies', 39.6, 60, 88, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Water - Aquafina Vitamin', 20.84, 69, 86, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Beringer Founders Estate', 21.79, 96, 99, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chocolate - Milk Coating', 16.1, 45, 23, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Eggplant Oriental', 2.53, 88, 81, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Eel - Smoked', 23.43, 75, 63, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Calaloo', 64.54, 70, 76, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Flower - Commercial Bronze', 57.37, 64, 9, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Foam Espresso Cup Plain White', 94.65, 56, 56, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Island Oasis - Ice Cream Mix', 32.14, 15, 69, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tuna - Salad Premix', 16.64, 98, 49, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sponge Cake Mix - Vanilla', 23.37, 4, 79, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cilantro / Coriander - Fresh', 24.9, 43, 45, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sugar - Individual Portions', 40.19, 15, 22, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cake - Mini Potato Pancake', 51.45, 71, 38, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chips Potato Swt Chilli Sour', 98.36, 86, 95, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Wine - Sogrape Mateus Rose', 59.4, 73, 19, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sultanas', 34.3, 83, 55, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Chicken - Breast, 5 - 7 Oz', 29.92, 52, 85, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Salt - Table', 63.91, 22, 12, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Crab - Meat', 21.54, 5, 96, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beets - Mini Golden', 14.89, 21, 94, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Crab Meat Claw Pasteurise', 10.44, 47, 74, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('V8 - Vegetable Cocktail', 79.07, 90, 90, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Carbonated Water - Strawberry', 87.67, 71, 40, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pail For Lid 1537', 15.12, 59, 84, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Tart - Pecan Butter Squares', 50.96, 50, 60, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Ham - Cooked Bayonne Tinned', 11.24, 40, 29, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Lentils - Green Le Puy', 40.28, 20, 93, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Couscous', 49.31, 78, 73, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Sugar - White Packet', 55.02, 89, 37, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Buffalo - Tenderloin', 53.49, 49, 98, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bread - Onion Focaccia', 8.13, 58, 99, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Amarula Cream', 35.47, 76, 39, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Syrup - Golden, Lyles', 19.98, 16, 93, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Appetizer - Lobster Phyllo Roll', 16.4, 45, 14, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pepper - Sorrano', 43.7, 30, 54, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Parasol Pick Stir Stick', 90.7, 41, 77, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Breadfruit', 17.62, 45, 43, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cloves - Ground', 17.24, 61, 65, 4);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Rum - Coconut, Malibu', 73.75, 91, 70, 1);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Beans - Navy, Dry', 82.7, 11, 30, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cranberries - Dry', 97.55, 63, 76, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Pizza Pizza Dough', 52.77, 23, 56, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Nantucket - Carrot Orange', 29.03, 64, 81, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bar Mix - Pina Colada, 355 Ml', 62.27, 23, 42, 3);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Steam Pan Full Lid', 30.78, 36, 62, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Cheese - Parmigiano Reggiano', 9.2, 23, 42, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Bacardi Breezer - Tropical', 4.37, 33, 56, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Apricots - Halves', 25.3, 25, 59, 2);
insert into Sales_product (name, price, no_available, no_of_intake, category_id) values ('Peas Snow', 26.44, 2, 28, 4);
