# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('status', models.CharField(choices=[('O', 'Occupied'), ('U', 'Unoccupied'), ('B', 'Booked')], max_length=30)),
                ('occupied', models.CharField(choices=[('G', 'Good'), ('B', 'Bad'), ('E', 'Excellent')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Roomclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('unique_color', models.CharField(blank=True, max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='roomclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.Roomclass'),
        ),
    ]
